baseURL = 'https://resumen.flor.cez.ar/'
languageCode = 'en-us'
title = 'Notas de la facu'
theme = 'PaperModX'
defaultOutputFormat = 'html'

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[params]
math = true
disableSpecial1stPost = true
